import Controllers.GameController as GameController
import Controllers.UserController as UserController
import Controllers.GenreController as GenreController
import Controllers.DeveloperController as DeveloperController
import Controllers.PublisherController as PublisherController
import Controllers.RolesController as RolesController
import Controllers.CommentController as CommentController
